name: scrybe-app

services:
  # =================
  # |  API pública  |
  # =================
  api:
    image: golang:1.26.2
    container_name: scrybe-api
    working_dir: /app
    volumes:
      - ./apps/api:/app
    command: go run ./cmd/api
    env_file:
      - .env
    environment:
      API_ADDR: ${API_ADDR:-:8081}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8081:8081"
    restart: unless-stopped
  

  # ===================
  # |  Documentación  |
  # ===================
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: scrybe-swagger-ui
    environment:
      SWAGGER_JSON: /spec/openapi.yaml
    volumes:
      - ./docs/api/openapi.yaml:/spec/openapi.yaml:ro
    ports:
      - "8082:8080"
    restart: unless-stopped